version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_URL=${API_URL:-http://127.0.0.1:1234/v1/chat/completions}
      - MODEL_NAME=${MODEL_NAME:-qwen/qwen3-1.7b}
      - MAX_TOKENS=${MAX_TOKENS:-1000}
      - TEMPERATURE=${TEMPERATURE:-0.7}
    volumes:
      # Mount static files for development (optional)
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  llm:
    image: localai/localai:latest
    container_name: localai
    ports:
      - "1234:8080"
    environment:
      - MODELS_PATH=/models
      - PRELOAD_MODELS=[{"name":"my-gguf","url":"huggingface://Qwen/Qwen3-1.7B-GGUF/Qwen3-1.7B-Q8_0.gguf","overrides":{"backend":"llama-cpp","f16":false}}]
    volumes:
      - models:/models
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8080/readyz >/dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    restart: unless-stopped

volumes:
  models:

networks:
  default:
    driver: bridge