version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_URL=${API_URL:-http://127.0.0.1:1234/v1/chat/completions}
      - MODEL_NAME=${MODEL_NAME:-qwen/qwen3-1.7b}
      - MAX_TOKENS=${MAX_TOKENS:-1000}
      - TEMPERATURE=${TEMPERATURE:-0.7}
    volumes:
      # Mount static files for development (optional)
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge